consensus-layer:
  url: "http://127.0.0.1"
  port: 59222

execution-layer:
  development:
    url: "http://127.0.0.1"
    port: 59217
  kurtosis:
    url: "http://host.docker.internal"
    port: 59217
  # TODO: Add production URL + replace with env variable
  production:
    url: "http://actual-production-url"
    port: 8545

environment: "${ENVIRONMENT}"  